[% warning %]

name: [% test_type %] ([% test_configuration %])

[% triggers %]

[% pr_pattern %]

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  REPO: [% repo %]
  ARCH: [% arch %]
[% linux_env %]
  COMPILER_TYPE: [% compiler_type %]
  COMPILER: [% compiler %]
  BUILD_TYPE: [% build_type %]
  ULIMIT_CORE: [% ulimit_core %]
  CODE_COVERAGE: [% code_coverage %]
  VT_LB: [% vt_lb %]
  VT_TRACE: [% vt_trace %]
  VT_TRACE_RT: [% vt_trace_rt %]
  VT_TRACE_ONLY: [% vt_trace_only %]
  VT_MIMALLOC: [% vt_mimalloc %]
  VT_DOCS: [% vt_docs %]
  VT_ASAN: [% vt_asan %]
  VT_WERROR: [% vt_werror %]
  VT_POOL: [% vt_pool %]
  VT_EXTENDED_TESTS: [% vt_extended_tests %]
  VT_UNITY_BUILD: [% vt_unity_build %]
  VT_PRODUCTION_BUILD: [% vt_production_build %]
  VT_FCONTEXT: [% vt_fcontext %]
  VT_USE_OPENMP: [% vt_use_openmp %]
  VT_USE_STD_THREAD: [% vt_use_std_thread %]
  VT_ZOLTAN: [% vt_zoltan %]
  VT_CI_BUILD: [% vt_ci_build %]
  VT_DIAGNOSTICS: [% vt_diagnostics %]
  CACHE: "$(Agent.TempDirectory)/cache/"
  cache_name: [% cache_name %]
  build_root: "$(CACHE)/[% build_root %]/"
  TS: 0
  TS_YEAR: 0
  TS_MONTH: 0
  TS_DAY: 0

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      [% workflow_runs_on %]
    timeoutInMinutes: 180
    steps:
      - task: Bash@3
        displayName: Job setup
        inputs:
          targetType: 'inline'
          script: |
            [% job_setup %]
      - task: Bash@3
        displayName: Build timestamp for caching
        inputs:
          targetType: 'inline'
          script: |
            echo 'string(TIMESTAMP current_date "%H;%M;%S" UTC)' > script
            echo 'execute_process(COMMAND ${CMAKE_COMMAND} -E echo "${current_date}")' >> script
            val=$(cmake -P script)
            echo "##vso[task.setvariable variable=TS]$val"
            echo 'string(TIMESTAMP current_date "%Y" UTC)' > script
            echo 'execute_process(COMMAND ${CMAKE_COMMAND} -E echo "${current_date}")' >> script
            val=$(cmake -P script)
            echo "##vso[task.setvariable variable=TS_YEAR]$val"
            echo 'string(TIMESTAMP current_date "%m" UTC)' > script
            echo 'execute_process(COMMAND ${CMAKE_COMMAND} -E echo "${current_date}")' >> script
            val=$(cmake -P script)
            echo "##vso[task.setvariable variable=TS_MONTH]$val"
            echo 'string(TIMESTAMP current_date "%d" UTC)' > script
            echo 'execute_process(COMMAND ${CMAKE_COMMAND} -E echo "${current_date}")' >> script
            val=$(cmake -P script)
            echo "##vso[task.setvariable variable=TS_DAY]$val"
      - task: Bash@3
        displayName: Output timestamp for caching
        inputs:
          targetType: 'inline'
          script: 'echo "my pipeline variable is $(TS) $(TS_YEAR) $(TS_MONTH) $(TS_DAY)"'
      - task: Cache@2
        displayName: Update cache
        inputs:
          securityNamespace: cache
          key: $(Agent.OS) | "$(cache_name)" | $(TS_YEAR) | $(TS_MONTH) | $(TS_DAY) | $(TS)
          path: '$(build_root)/ccache'
          restoreKeys: |
            $(Agent.OS) | "$(cache_name)" | $(TS_YEAR) | $(TS_MONTH) | $(TS_DAY)
            $(Agent.OS) | "$(cache_name)" | $(TS_YEAR) | $(TS_MONTH)
            $(Agent.OS) | "$(cache_name)" | $(TS_YEAR)
            $(Agent.OS) | "$(cache_name)"
      - task: Bash@3
        displayName: Check for changes in containers
        inputs:
          targetType: 'inline'
          script: |
            val=$(./scripts/check_containers.sh)
            echo "##vso[task.setvariable variable=compose_command]$val"
      - task: DockerCompose@0
        displayName: Pull container
        inputs:
          containerregistrytype: 'Container Registry'
          dockerComposeFile: '**/docker-compose.yml'
          action: 'Run a Docker Compose command'
          dockerComposeCommand: '$(compose_command) [% docker_target %]'
      - task: DockerCompose@0
        displayName: Build container
        inputs:
          containerregistrytype: 'Container Registry'
          dockerComposeFile: '**/docker-compose.yml'
          action: 'Run a Docker Compose command'
          dockerComposeCommand: 'run [% docker_target %]'
      - task: Bash@3
        displayName: Put compilation's and tests' logs in PR comment
        condition: and(succeededOrFailed(), eq(variables['Build.Reason'], 'PullRequest'))
        inputs:
          targetType: 'inline'
          script: |
            ./scripts/report_logs_in_comment.sh                     \
                "$(build_root)/vt/compilation_errors_warnings.out"  \
                "$(build_root)/vt/cmake-output.log"                 \
                "$(Build.BuildNumber)"                              \
                "$(System.PullRequest.PullRequestNumber)"           \
                "$(Build.Repository.Name)"                          \
                "$GITHUB_PAT"                                       \
                "$(Build.BuildId)"                                  \
                "$(System.JobId)"

        env:
          GITHUB_PAT: $(github_pat)
      - task: DockerCompose@0
        displayName: Push container to registry
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: 'dockerRegistryConnection1'
          dockerComposeFile: '**/docker-compose.yml'
          action: 'Run a Docker Compose command'
          dockerComposeCommand: 'push [% docker_target %]'
      - task: Bash@3
        displayName: Create artifacts
        inputs:
          targetType: 'inline'
          script: |
            zip -j $(Agent.TempDirectory)/LastTest.log.gz $(build_root)/vt/Testing/Temporary/LastTest.log
            zip -j $(Agent.TempDirectory)/cmake-output.log.gz $(build_root)/vt/cmake-output.log
      - task: PublishPipelineArtifact@1
        displayName: Upload CMake test output artifact
        inputs:
          targetPath: '$(Agent.TempDirectory)/LastTest.log.gz'
          artifact: 'CMakeLastTestLog'
          publishLocation: 'pipeline'
      - task: PublishPipelineArtifact@1
        displayName: Upload CMake full output artifact
        inputs:
          targetPath: '$(Agent.TempDirectory)/cmake-output.log.gz'
          artifact: 'CMakeOutputLog'
          publishLocation: 'pipeline'
