include(CheckCXXCompilerFlag)

function(enable_cxx_compiler_flag_if_supported flag var)
  string(FIND "${CMAKE_CXX_FLAGS}" "${flag}" flag_already_set)
  if(flag_already_set EQUAL -1)
    check_cxx_compiler_flag("${flag}" ${var})
    if(flag_supported)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${flag}" PARENT_SCOPE)
    endif()
  endif()
endfunction()

get_directory_property(hasParent PARENT_DIRECTORY)
if(NOT hasParent)
  enable_cxx_compiler_flag_if_supported("-Wall" VT_WALL_FLAG_SUPPORTED)
  enable_cxx_compiler_flag_if_supported("-pedantic" VT_PEDANTIC_FLAG_SUPPORTED)
  enable_cxx_compiler_flag_if_supported("-Wshadow" VT_WSHADOW_FLAG_SUPPORTED)
  enable_cxx_compiler_flag_if_supported("-Wno-unknown-pragmas" VT_WNO_UNKNOWN_PRAGMAS_FLAG_SUPPORTED)
  enable_cxx_compiler_flag_if_supported("-Wsign-compare" VT_WSIGN_COMPARE_SUPPORTED)
  # Not really a warning, is still diagnostic related..
  enable_cxx_compiler_flag_if_supported("-ftemplate-backtrace-limit=100" VT_FTEMPLATE_BACKTRACE_LIMIT_SUPPORTED)
endif()
