name: Build & Push Docker images

on:
  push:
    branches:
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List targets
        id: list-targets
        uses: docker/bake-action/subaction/list-targets@v6
        with:
          target: vt-build-all

  bake:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}

    steps:
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/bake-action@v6
        with:
          targets: ${{ matrix.target }}
          push: true
