name: Check header guards and license

on: pull_request

jobs:
  check-guards:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: actions/setup-python@v5
        with:
            python-version: '3.7'

      - name: Check that for correct include guards and license
        run: ./scripts/check_guards.sh $(pwd)
