name: PR checks (commit format)

on: pull_request

jobs:
  check:
    name: Check commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch base_ref HEAD
        run: git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}
      - name: Display base sha
        shell: bash
        run: echo "${{ github.event.pull_request.base.sha }}"
      - uses: DARMA-tasking/check-commit-format@master
        with:
          revision: ${{ github.event.pull_request.base.sha }}
