name: Check License

on: pull_request

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libfile-find-rule-perl

    - name: Check license
      shell: bash
      run: ./scripts/check_license.sh $(pwd)
