name: Develop CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List targets
        id: list-targets
        uses: docker/bake-action/subaction/list-targets@v6
        with:
          target: vt-develop

  bake:
    needs:
      - prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/cache@v4
        with:
          path: docker-output/build/ccache
          key: ${{ matrix.target }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ matrix.target }}-${{ github.ref }}
            ${{ matrix.target }}-

      - name: Build
        uses: docker/bake-action@v6
        with:
          source: .
          targets: ${{ matrix.target }}
          files: docker-bake.hcl
