name: PR tests (clang-5.0, ubuntu, mpich, trace)

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - develop
      - 1.*
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      REPO: lifflander1/vt
      ARCH: amd64
      UBUNTU: 18.04
      COMPILER_TYPE: clang
      COMPILER: clang-5.0
      BUILD_TYPE: release
      ULIMIT_CORE: 0
      VT_LB: 1
      VT_TRACE: 1
      VT_TRACE_RT: 0
      VT_MIMALLOC: 0
      VT_DOCS: 0
      VT_ASAN: 0
      CACHE: ~/.local/cache/

    steps:
    - uses: actions/cache@v1
      with:
        path: ~/.local/cache/amd64*/ccache/
        key: ${{ runner.os }}-ubuntu-clang-5.0-ccache-${{ hashFiles('**/*') }}
        restore-keys: |
          ${{ runner.os }}-ubuntu-clang-5.0-ccache-
    - uses: actions/checkout@v2
    - name: Docker Pull Base Image
      shell: bash
      run: docker-compose pull --ignore-pull-failures ubuntu-cpp
    - name: Build the Docker image
      run: docker-compose run ubuntu-cpp
    - name: Docker Push Base Image
      if: success()
      continue-on-error: true
      shell: bash
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} \
                     -p ${{ secrets.DOCKER_PASSWORD }}
        docker-compose push ubuntu-cpp
