name: PR tests (gcc-7, ubuntu, mpich, trace runtime, LB)

on:
  push:
    branches:
      - develop
      - 1.*
  pull_request

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile-ubuntu-gcc-7 --build-arg TRACE_RUNTIME_ENABLED=1 --build-arg TRACE_ENABLED=1 --build-arg LB_ENABLED=1 --tag vt:$(date +%s)
