name: PR tests (gcc-5, ubuntu, mpich)

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - develop
      - 1.*
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      REPO: lifflander1/vt
      ARCH: amd64
      UBUNTU: 18.04
      COMPILER_TYPE: gnu
      COMPILER: gcc-5
      BUILD_TYPE: release
      ULIMIT_CORE: 0
      VT_LB: 1
      VT_TRACE: 0
      VT_TRACE_RT: 0
      VT_MIMALLOC: 0
      VT_DOCS: 0
      VT_ASAN: 0
      CACHE: ~/.local/cache/

    steps:
    - uses: actions/cache@v1
      with:
        path: ~/.local/cache/
        key: ${{ runner.os }}-ubuntu-gcc-5-${{ hashFiles('**/*') }}
        restore-keys: |
          ${{ runner.os }}-ubuntu-gcc-5-
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose run ubuntu-cpp
