name: PR tests (gcc-5, ubuntu, mpich)

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - develop
      - 1.*
  pull_request:
    branches:
      - *

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile-ubuntu --tag vt:$(date +%s)
