
name: Force building PR in draft mode

on:
  pull_request:
    types:
      - labeled

jobs:
  build_clang-39-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: clang-3.9, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (clang-3.9, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_clang-5-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: clang-5.0, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (clang-5.0, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_clang-9-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: clang-9, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (clang-9, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_clang-10-alpine-mpich:
    if: github.event.label.name == 'force-build'
    name: clang-10, alpine, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (clang-10, alpine, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_clang-10-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: clang-10, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (clang-10, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_clang-11-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: clang-11, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (clang-11, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_clang-12-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: clang-12, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (clang-12, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_clang-13-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: clang-13, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (clang-13, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_clang-14-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: clang-14, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (clang-14, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

  build_gcc-5-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: gcc-5, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (gcc-5, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_gcc-6-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: gcc-6, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (gcc-6, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_gcc-7-ubuntu-mpich-trace-runtime-LB:
    if: github.event.label.name == 'force-build'
    name: gcc-7, ubuntu, mpich, trace runtime, LB
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (gcc-7, ubuntu, mpich, trace runtime, LB)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_gcc-8-ubuntu-mpich-asan:
    if: github.event.label.name == 'force-build'
    name: gcc-8, ubuntu, mpich, address sanitizer
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (gcc-8, ubuntu, mpich, address sanitizer)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_gcc-9-ubuntu-mpich-zoltan:
    if: github.event.label.name == 'force-build'
    name: gcc-9, ubuntu, mpich, zoltan
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (gcc-9, ubuntu, mpich, zoltan)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_gcc-10-ubuntu-openmpi-no-LB:
    if: github.event.label.name == 'force-build'
    name: gcc-10, ubuntu, openmpi, no LB
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (gcc-10, ubuntu, openmpi, no LB)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_gcc-11-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: gcc-11, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (gcc-11, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_gcc-12-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: gcc-12, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (gcc-12, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_icpx-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: intel icpx, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (intel icpx, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_nvcc-10-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: nvidia cuda 10.1, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (nvidia cuda 10.1, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  build_nvcc-11-ubuntu-mpich:
    if: github.event.label.name == 'force-build'
    name: nvidia cuda 11.0, ubuntu, mpich
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests (nvidia cuda 11.0, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
