name: Graph VT build times

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - develop
      # Remove later
      - 1216-graph-docker-build-times

jobs:
  graph:
    runs-on: ubuntu-latest
    steps:
    - name: Generate and push graph
      uses: DARMA-tasking/graph-build-times@1-create-the-github-action
      with:
        github_personal_token: ${{ secrets.GH_PAT }}
        github_token: ${{ github.token }}
        workflow: pushdockerimage.yml
        filename: build_times.png
        num_last_build: 50
        title: Last 50 builds of vt:develop docker image
        graph_width: 19
        graph_height: 8
