name: PR tests (clang-14, macosx, mpich)

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, reopened, synchronize, converted_to_draft, ready_for_review]

concurrency:
  group: ${{ github.event.repository.name }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: macos-12

    if: github.event.pull_request.draft == false

    strategy:
      fail-fast: false

    env:
      CMAKE_BUILD_TYPE: release
      VT_LB_ENABLED: 1
      VT_TRACE_ENABLED: 1
      VT_WERROR: 1
      CMAKE_CXX_STANDARD: 17
      CMAKE_GENERATOR: "Unix Makefiles"
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-macosx-clang-14-ccache-${{ secrets.GH_ACTIONS_CACHE_VERSION }}-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-macosx-clang-14-ccache-${{ secrets.GH_ACTIONS_CACHE_VERSION }}
      - uses: actions/cache@v3
        id: mpich-cache
        with:
          path: ~/.mpich
          key: ${{ runner.os }}-macosx-clang-14-mpich-${{ hashFiles('**/.github/workflows/macosx-clang-mpich.yml', '**/ci/deps/mpich.sh') }}
      - name: Install Dependencies
        shell: bash
        run: brew bundle --file=ci/Brewfile
      - name: Modify hosts file
        shell: bash
        run: echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
      - name: Build mpich
        if: steps.mpich-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          ci/deps/mpich.sh 3.3.2 -j4 $(grealpath ~/.mpich)
      - name: Build
        shell: bash
        run: |
          PATH=~/.mpich/bin:$PATH ci/build_cpp.sh $(pwd) $(pwd)/build
      - name: Test
        shell: bash
        run: |
          PATH=~/.mpich/bin:$PATH ci/test_cpp.sh $(pwd) $(pwd)/build
