name: PR tests (clang-8, macosx, mpich)

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - develop
      - 1.*
  pull_request:

jobs:

  build:

    runs-on: macos-10.15

    strategy:
      fail-fast: false

    env:
      CMAKE_BUILD_TYPE: release
      VT_LB_ENABLED: 1
      VT_TRACE_ENABLED: 1
      VT_USE_OPENMP: 0
      VT_USE_STD_THREAD: 0
      VT_WERROR: 1
      CMAKE_GENERATOR: "Unix Makefiles"
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-macosx-clang-8-ccache-${{ secrets.GH_ACTIONS_CACHE_VERSION }}-${{ hashFiles('**/*') }}
        restore-keys: |
          ${{ runner.os }}-macosx-clang-8-ccache-${{ secrets.GH_ACTIONS_CACHE_VERSION }}
    - uses: actions/cache@v2
      id: mpich-cache
      with:
        path: /path/to/mpich
        key: ${{ runner.os }}-macosx-clang-8-mpich-${{ hashFiles('**/.github/workflows/macosx-clang-mpich.yml') }}
    - name: Install Dependencies
      shell: bash
      run: brew bundle --file=ci/Brewfile
    - name: Modify hosts file
      shell: bash
      run: echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
    - name: Build mpich
      shell: bash
      run: |
        ci/deps/mpich.sh 3.3.2 -j4
    - name: Build
      shell: bash
      run: ci/build_cpp.sh $(pwd) $(pwd)/build
    - name: Test
      shell: bash
      run: |
        ci/test_cpp.sh $(pwd) $(pwd)/build
