name: PR tests (clang-tidy)

on:
  push:
    branches:
      - develop
      - 1.*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_TYPE: release
      VT_LB_ENABLED: 1
      VT_TRACE_ENABLED: 1
      VT_USE_OPENMP: 0
      VT_USE_STD_THREAD: 0

    steps:
      - uses: actions/checkout@v2
      - name: Run clang-tidy docker
        shell: bash
        run: docker build -f ci/docker/vt-clang-tidy.dockerfile -t vt-clang-tidy .
