name: PR checks (git --check)

on: pull_request

jobs:
  check:
    name: Run git check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch base_ref HEAD
        run: git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}
      - name: Display base sha
        shell: bash
        run: echo "${{ github.event.pull_request.base.sha }}"
      - uses: joel-coffman/action-git-diff-check@0.1
        with:
          revision: ${{ github.event.pull_request.base.sha }}
