name: PR checks (git --check)

on: pull_request

jobs:
  check:
    name: Run git check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display base sha
        shell: bash
        run: echo "${{ github.base_ref }}"
      - uses: joel-coffman/action-git-diff-check@0.1
        with:
          revision: ${{ github.base_ref }}
