name: PR checks (git --check)

on: pull_request

jobs:
  check:
    name: Run git check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display base sha
        shell: bash
        run: echo "${{ github.context.pull_request.base.sha }}"
      - uses: actions/git-diff-check@v1
        with:
          revision: ${{ github.context.pull_request.base.sha }}
