
name: Spawn tests extended (intel 18.03, ubuntu, mpich)

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: github.event.label.name == 'runextendedtests'
    name: Invoke Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/DARMA-tasking/DARMA
          azure-pipeline-name: 'PR tests extended (intel 18.03, ubuntu, mpich)'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
