name: Spawn extended tests (CUDA 12.9, Intel oneAPI)

on:
  pull_request:
    types:
      - labeled

concurrency:
  group: extended-tests-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  extended-tests:
    if: github.event.label.name == 'runextendedtests'
    name: Invoke Github Pipeline
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - vt-build-amd64-ubuntu-20-04-gcc-9-cuda-11-4-3-cpp
          - vt-build-amd64-ubuntu-24-04-gcc-13-cuda-12-9-0-cpp
          - vt-build-amd64-ubuntu-24-04-icpx-cpp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore ccache
        id: ccache-archive
        uses: actions/cache@v4
        with:
          path: ccache-archive
          key: extended-${{ matrix.target }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            extended-${{ matrix.target }}-${{ github.ref }}-
            extended-${{ matrix.target }}-

      - name: Inject ccache
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-map: |
            {
              "ccache-archive": {
                "target": "/build/ccache",
                "id": "${{ matrix.target }}-extended"
              }
            }
          skip-extraction: ${{ steps.ccache-archive.outputs.cache-hit }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and run extended tests
        id: build-image
        uses: docker/bake-action@v6
        with:
          source: .
          targets: ${{ matrix.target }}
          files: docker-bake.hcl
          push: false
          set: |
            *.args.CACHE_ID=${{ matrix.target }}-extended
            *.args.VT_EXTENDED_TESTS_ENABLED=1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
